mar <- c(1.5,0.8,1.5,0.8)
require(Rvasp)
data(silverslab)
temppos <- poscar.getshapedposcar(silverslab,x=10,y=10)
# left plot - top view
png("examples/poscar_top.png", width=400,height=375)
par(mar=mar)
plot(temppos,basis=F,unitcell=T)
plot.poscar.addlayers(poscar=temppos,layer=1:2,layers=12,color=c("red","blue"),size=4)
plot.poscar.addnumbers(poscar=temppos,layer=1:2,layers=12)
plot.atoms.adddistance(atoms=temppos$atoms[c(17,161),],basis=temppos$basis*temppos$a,selectedsize=4)
dev.off()
# right plot - side view
png("examples/poscar_side.png", width=300,height=375)
par(mar=mar)
plot(temppos,basis=F,unitcell=F,direction=1)
plot.poscar.addlayers(poscar=temppos,layer=1:2,layers=12,color=c("red","blue"),size=4,direction=1)
plot.poscar.addlayerdistance(poscar=temppos,layer=1:2,layers=12,direction=1)
plot.poscar.addlayers(poscar=temppos,layer=3:12,layers=12,color="grey",size=4,direction=1)
dev.off()
# STM
png("examples/stm.png", width=700,height=375)
data(silverstm)
plot.stm(silverstm,super=5,xlab="x (nm)",ylab="y (nm)")
plot.stm.addunitcell(silverstm,atomnumber=1)
plot.stm.addatoms(silverstm,super=5,xlim=c(0,0.75),ylim=c(0,0.75),atomselector=1,atomsize=10,col="red")
plot.stm.addatoms(silverstm,super=5,xlim=c(0,0.75),ylim=c(0,0.75),atomselector=2,atomsize=10,col="blue")
dev.off()
# Bands and dos
png("examples/bands.png", width=500,height=375)
par(mar=c(4,4,0.8,0.8))
data(silverbands)
data(silverdos)
newfermi <- silverbands$efermi-silverdos$efermi
bands<-plot.bandsdata(silverbands,sym.labels=c(expression(Gamma),"L","W","X",expression(Gamma),"K","X"),fermi=T,ylim=c(-10,20),energyoffset=newfermi)
proj <- bandsdata.getprojecteddata(bands)
plot.projectedbands.add(proj,orbitals=c(1,2,3,4),cex=1,legendcex=1.2)
dev.off()
png("examples/dos.png", width=200,height=375)
par(mar=c(4,4,0.8,0.8))
dosdata <- plot.dosdata(silverdos,flip=T,fermi=T,col.fermi="Blue",xlim=c(0,0.5),ylim=c(-10,20))
plot.dosdata.add(dosdata,orbitals=c(1:4,"all"),type="polygon",col=c(colorRampPalette(c("red","blue","green"))(4),"grey"))
dev.off()
# Elevated Bandstructure
png("examples/ebands.png", width=700,height=375)
par(mar=c(4,4+8,0.8,0.8+8))
data(silverbands)
data(silverdos)
newfermi <- silverbands$efermi-silverdos$efermi
bands<-plot.bandsdata(silverbands,sympointpath=list(c(1,2),c(2,3),c(3,4),c(7,6)),sym.labels=c(expression(Gamma),"L","W","X",expression(Gamma),"K","X"),fermi=T,ylim=c(-10,20),energyoffset=newfermi)
proj <- bandsdata.getprojecteddata(bands)
plot.projectedbands.add(proj,orbitals=c(1,2,3,4),cex=1,legendcex=1.2)
zoomplot(xpos=c(36,53),ypos=c(58,70),xmean=0.35,xwidth=0.025,ymean=6.1,ywidth=1,xaxt="n",lines=F)
plot.bandsdata.addbands(bands)
plot.bandsdata.addsymnnames(bands,labels=c(expression(Gamma),"L","W","X",expression(Gamma),"K","X"))
plot.projectedbands.add(proj,orbitals=c(1,2,3,4),cex=1,legend=NULL)
endzoomplot()
dev.off()
# E over a
png("examples/eaplot.png", width=700,height=375)
par(mar=c(4,4+10,0.8,0.8+10))
data(silverea)
plot.calculation.ea(silverea$LDA,energyshift=silverea$LDAsingleAtom$a_20.000$energy,ylim=c(-3.8,-2.1))
plot.calculation.ea.addpoints(silverea$GGA,energyshift=silverea$GGAsingleAtom$a_20.000$energy,pch=3)
dev.off()
# Bulk bands
png("examples/bulkbands.png", width=700,height=375)
par(mar=c(4,4+7,0.8,0.8+7))
load("examples/silverbulkbands.RData")
bandsdata <- silverbulkbands$slab$a_4.030$banddata
bulkbands <- calculation.getbulkbands(silverbulkbands$bulk)
plot.bandsdata(bandsdata,type="n",sym.lty=NA,fermi=F,ylim=c(-10,10))
plot.bulkbands.add(bulkbands)
plot.bandsdata.addbands(bandsdata=bandsdata,col="black")
plot.bandsdata.addfermi(bandsdata)
plot.bandsdata.addsymnnames(bandsdata,labels=c(expression(Gamma),"M","K",expression(Gamma)))
dev.off()
#Brillouinzones
png("examples/brillouinzone.png", width=700,height=375)
par(mar=c(0.8,4+7,0.8,0.8+7))
data(silverslab)
bzs<-poscar.getbrillouinzones(silverslab)
plot(bzs)
superslab <- poscar.createsupercell(silverslab,A=diag(c(2,2,1))) # 2x2x1 supercell
bzs2<-poscar.getbrillouinzones(superslab,extend=2)
plot.brillouinzones.add(bzs2,col="red")
plot.brillouinzones.addsympoints(brillouinzone=bzs,directcoordinates=list(c(1,0),c(0,0),c(1/2,1/2)),labels=c("K",expression(Gamma),"M"))
plot.brillouinzones.addsympoints(brillouinzone=bzs,directcoordinates=list(c(1,0),c(0,0),c(1/2,1/2)),labels=c("K",expression(Gamma),expression(Gamma)),textpos=4,col="red")
dev.off()
#PT
png("examples/periodic_table.png", width=700,height=375)
par(mar=c(0.8,0.8,0.8,0.8))
plot.periodictable(highlights=1:2,highlighttexts=list(1.008,4.0026),underlay=3:10)
dev.off()
